# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 13:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, verbose_name='\u7f51\u9875\u5730\u5740')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('brows', models.IntegerField(default=0, null=True, verbose_name='\u6d4f\u89c8\u91cf')),
                ('abstract', models.TextField(default=django.utils.timezone.now, null=True, verbose_name='\u6458\u8981')),
                ('label', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='\u6807\u7b7e'), null=True, size=None)),
                ('image', models.URLField(null=True, verbose_name='\u56fe\u7247\u8def\u5f84')),
                ('image_file', models.FilePathField(null=True, path=None, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('tmp', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
